// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=chunk
//

// Package chunk is a generated GoMock package.
package chunk

import (
	context "context"
	types "dos/internal/common/types"
	storage "dos/internal/services/storage"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockChunkConfig is a mock of ChunkConfig interface.
type MockChunkConfig struct {
	ctrl     *gomock.Controller
	recorder *MockChunkConfigMockRecorder
	isgomock struct{}
}

// MockChunkConfigMockRecorder is the mock recorder for MockChunkConfig.
type MockChunkConfigMockRecorder struct {
	mock *MockChunkConfig
}

// NewMockChunkConfig creates a new mock instance.
func NewMockChunkConfig(ctrl *gomock.Controller) *MockChunkConfig {
	mock := &MockChunkConfig{ctrl: ctrl}
	mock.recorder = &MockChunkConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkConfig) EXPECT() *MockChunkConfigMockRecorder {
	return m.recorder
}

// FrameSize mocks base method.
func (m *MockChunkConfig) FrameSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FrameSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FrameSize indicates an expected call of FrameSize.
func (mr *MockChunkConfigMockRecorder) FrameSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FrameSize", reflect.TypeOf((*MockChunkConfig)(nil).FrameSize))
}

// MockChunkStorage is a mock of ChunkStorage interface.
type MockChunkStorage struct {
	ctrl     *gomock.Controller
	recorder *MockChunkStorageMockRecorder
	isgomock struct{}
}

// MockChunkStorageMockRecorder is the mock recorder for MockChunkStorage.
type MockChunkStorageMockRecorder struct {
	mock *MockChunkStorage
}

// NewMockChunkStorage creates a new mock instance.
func NewMockChunkStorage(ctrl *gomock.Controller) *MockChunkStorage {
	mock := &MockChunkStorage{ctrl: ctrl}
	mock.recorder = &MockChunkStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkStorage) EXPECT() *MockChunkStorageMockRecorder {
	return m.recorder
}

// AcquireOpSlot mocks base method.
func (m *MockChunkStorage) AcquireOpSlot(arg0 context.Context, arg1 time.Duration) (func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireOpSlot", arg0, arg1)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireOpSlot indicates an expected call of AcquireOpSlot.
func (mr *MockChunkStorageMockRecorder) AcquireOpSlot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireOpSlot", reflect.TypeOf((*MockChunkStorage)(nil).AcquireOpSlot), arg0, arg1)
}

// DeleteChunk mocks base method.
func (m *MockChunkStorage) DeleteChunk(arg0 context.Context, arg1 types.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChunk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChunk indicates an expected call of DeleteChunk.
func (mr *MockChunkStorageMockRecorder) DeleteChunk(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChunk", reflect.TypeOf((*MockChunkStorage)(nil).DeleteChunk), arg0, arg1)
}

// LoadChunk mocks base method.
func (m *MockChunkStorage) LoadChunk(arg0 types.ChunkID) (types.Chunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadChunk", arg0)
	ret0, _ := ret[0].(types.Chunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadChunk indicates an expected call of LoadChunk.
func (mr *MockChunkStorageMockRecorder) LoadChunk(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadChunk", reflect.TypeOf((*MockChunkStorage)(nil).LoadChunk), arg0)
}

// ScheduleForwardChunk mocks base method.
func (m *MockChunkStorage) ScheduleForwardChunk(arg0 context.Context, arg1 types.ChunkID, arg2 []types.NodeRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleForwardChunk", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScheduleForwardChunk indicates an expected call of ScheduleForwardChunk.
func (mr *MockChunkStorageMockRecorder) ScheduleForwardChunk(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleForwardChunk", reflect.TypeOf((*MockChunkStorage)(nil).ScheduleForwardChunk), arg0, arg1, arg2)
}

// StartUpload mocks base method.
func (m *MockChunkStorage) StartUpload(arg0 context.Context, arg1 *types.ChunkMeta) (storage.UploadSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartUpload", arg0, arg1)
	ret0, _ := ret[0].(storage.UploadSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartUpload indicates an expected call of StartUpload.
func (mr *MockChunkStorageMockRecorder) StartUpload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartUpload", reflect.TypeOf((*MockChunkStorage)(nil).StartUpload), arg0, arg1)
}

// MockNodeIdentity is a mock of NodeIdentity interface.
type MockNodeIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockNodeIdentityMockRecorder
	isgomock struct{}
}

// MockNodeIdentityMockRecorder is the mock recorder for MockNodeIdentity.
type MockNodeIdentityMockRecorder struct {
	mock *MockNodeIdentity
}

// NewMockNodeIdentity creates a new mock instance.
func NewMockNodeIdentity(ctrl *gomock.Controller) *MockNodeIdentity {
	mock := &MockNodeIdentity{ctrl: ctrl}
	mock.recorder = &MockNodeIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeIdentity) EXPECT() *MockNodeIdentityMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockNodeIdentity) Validate(arg0 types.NodeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockNodeIdentityMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockNodeIdentity)(nil).Validate), arg0)
}
