// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -source=delivery.go -destination=mocks_test.go -package=delivery
//

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	chunkrpc "dos/internal/common/transport/chunkrpc"
	types "dos/internal/common/types"
	transport "dos/internal/services/client/transport"
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectDeliveryConfig is a mock of ObjectDeliveryConfig interface.
type MockObjectDeliveryConfig struct {
	ctrl     *gomock.Controller
	recorder *MockObjectDeliveryConfigMockRecorder
	isgomock struct{}
}

// MockObjectDeliveryConfigMockRecorder is the mock recorder for MockObjectDeliveryConfig.
type MockObjectDeliveryConfigMockRecorder struct {
	mock *MockObjectDeliveryConfig
}

// NewMockObjectDeliveryConfig creates a new mock instance.
func NewMockObjectDeliveryConfig(ctrl *gomock.Controller) *MockObjectDeliveryConfig {
	mock := &MockObjectDeliveryConfig{ctrl: ctrl}
	mock.recorder = &MockObjectDeliveryConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectDeliveryConfig) EXPECT() *MockObjectDeliveryConfigMockRecorder {
	return m.recorder
}

// TransferConcurrency mocks base method.
func (m *MockObjectDeliveryConfig) TransferConcurrency() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferConcurrency")
	ret0, _ := ret[0].(int)
	return ret0
}

// TransferConcurrency indicates an expected call of TransferConcurrency.
func (mr *MockObjectDeliveryConfigMockRecorder) TransferConcurrency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferConcurrency", reflect.TypeOf((*MockObjectDeliveryConfig)(nil).TransferConcurrency))
}

// MockChunkSource is a mock of ChunkSource interface.
type MockChunkSource struct {
	ctrl     *gomock.Controller
	recorder *MockChunkSourceMockRecorder
	isgomock struct{}
}

// MockChunkSourceMockRecorder is the mock recorder for MockChunkSource.
type MockChunkSourceMockRecorder struct {
	mock *MockChunkSource
}

// NewMockChunkSource creates a new mock instance.
func NewMockChunkSource(ctrl *gomock.Controller) *MockChunkSource {
	mock := &MockChunkSource{ctrl: ctrl}
	mock.recorder = &MockChunkSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkSource) EXPECT() *MockChunkSourceMockRecorder {
	return m.recorder
}

// Chunks mocks base method.
func (m *MockChunkSource) Chunks() iter.Seq2[types.ChunkKey, []byte] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chunks")
	ret0, _ := ret[0].(iter.Seq2[types.ChunkKey, []byte])
	return ret0
}

// Chunks indicates an expected call of Chunks.
func (mr *MockChunkSourceMockRecorder) Chunks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chunks", reflect.TypeOf((*MockChunkSource)(nil).Chunks))
}

// Err mocks base method.
func (m *MockChunkSource) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockChunkSourceMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockChunkSource)(nil).Err))
}

// MockMasterTransport is a mock of MasterTransport interface.
type MockMasterTransport struct {
	ctrl     *gomock.Controller
	recorder *MockMasterTransportMockRecorder
	isgomock struct{}
}

// MockMasterTransportMockRecorder is the mock recorder for MockMasterTransport.
type MockMasterTransportMockRecorder struct {
	mock *MockMasterTransport
}

// NewMockMasterTransport creates a new mock instance.
func NewMockMasterTransport(ctrl *gomock.Controller) *MockMasterTransport {
	mock := &MockMasterTransport{ctrl: ctrl}
	mock.recorder = &MockMasterTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterTransport) EXPECT() *MockMasterTransportMockRecorder {
	return m.recorder
}

// AllocateChunk mocks base method.
func (m *MockMasterTransport) AllocateChunk(arg0 context.Context, arg1 *transport.AllocateChunkCommand) (*types.ChunkAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateChunk", arg0, arg1)
	ret0, _ := ret[0].(*types.ChunkAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateChunk indicates an expected call of AllocateChunk.
func (mr *MockMasterTransportMockRecorder) AllocateChunk(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateChunk", reflect.TypeOf((*MockMasterTransport)(nil).AllocateChunk), arg0, arg1)
}

// CreateObject mocks base method.
func (m *MockMasterTransport) CreateObject(arg0 context.Context, arg1 types.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateObject indicates an expected call of CreateObject.
func (mr *MockMasterTransportMockRecorder) CreateObject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObject", reflect.TypeOf((*MockMasterTransport)(nil).CreateObject), arg0, arg1)
}

// DescribeObject mocks base method.
func (m *MockMasterTransport) DescribeObject(arg0 context.Context, arg1 types.ObjectID) (*types.ObjectDesc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeObject", arg0, arg1)
	ret0, _ := ret[0].(*types.ObjectDesc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeObject indicates an expected call of DescribeObject.
func (mr *MockMasterTransportMockRecorder) DescribeObject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeObject", reflect.TypeOf((*MockMasterTransport)(nil).DescribeObject), arg0, arg1)
}

// MockChunkTransport is a mock of ChunkTransport interface.
type MockChunkTransport struct {
	ctrl     *gomock.Controller
	recorder *MockChunkTransportMockRecorder
	isgomock struct{}
}

// MockChunkTransportMockRecorder is the mock recorder for MockChunkTransport.
type MockChunkTransportMockRecorder struct {
	mock *MockChunkTransport
}

// NewMockChunkTransport creates a new mock instance.
func NewMockChunkTransport(ctrl *gomock.Controller) *MockChunkTransport {
	mock := &MockChunkTransport{ctrl: ctrl}
	mock.recorder = &MockChunkTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkTransport) EXPECT() *MockChunkTransportMockRecorder {
	return m.recorder
}

// NewDownloadSession mocks base method.
func (m *MockChunkTransport) NewDownloadSession(arg0 []types.NodeRef, arg1 ...chunkrpc.SessionOption) chunkrpc.DownloadSession {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewDownloadSession", varargs...)
	ret0, _ := ret[0].(chunkrpc.DownloadSession)
	return ret0
}

// NewDownloadSession indicates an expected call of NewDownloadSession.
func (mr *MockChunkTransportMockRecorder) NewDownloadSession(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDownloadSession", reflect.TypeOf((*MockChunkTransport)(nil).NewDownloadSession), varargs...)
}

// NewUploadSession mocks base method.
func (m *MockChunkTransport) NewUploadSession(arg0 []types.NodeRef, arg1 ...chunkrpc.SessionOption) chunkrpc.UploadSession {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewUploadSession", varargs...)
	ret0, _ := ret[0].(chunkrpc.UploadSession)
	return ret0
}

// NewUploadSession indicates an expected call of NewUploadSession.
func (mr *MockChunkTransportMockRecorder) NewUploadSession(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUploadSession", reflect.TypeOf((*MockChunkTransport)(nil).NewUploadSession), varargs...)
}
