// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=admin
//

// Package admin is a generated GoMock package.
package admin

import (
	context "context"
	types "dos/internal/common/types"
	storage "dos/internal/services/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInventory is a mock of Inventory interface.
type MockInventory struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryMockRecorder
	isgomock struct{}
}

// MockInventoryMockRecorder is the mock recorder for MockInventory.
type MockInventoryMockRecorder struct {
	mock *MockInventory
}

// NewMockInventory creates a new mock instance.
func NewMockInventory(ctrl *gomock.Controller) *MockInventory {
	mock := &MockInventory{ctrl: ctrl}
	mock.recorder = &MockInventoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventory) EXPECT() *MockInventoryMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockInventory) GetStats() types.NodeStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats")
	ret0, _ := ret[0].(types.NodeStats)
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockInventoryMockRecorder) GetStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockInventory)(nil).GetStats))
}

// ListRecords mocks base method.
func (m *MockInventory) ListRecords() []storage.ChunkRecord {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecords")
	ret0, _ := ret[0].([]storage.ChunkRecord)
	return ret0
}

// ListRecords indicates an expected call of ListRecords.
func (mr *MockInventoryMockRecorder) ListRecords() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecords", reflect.TypeOf((*MockInventory)(nil).ListRecords))
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// StageAndReportAll mocks base method.
func (m *MockStorage) StageAndReportAll(arg0 context.Context) *storage.TriggerReportResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StageAndReportAll", arg0)
	ret0, _ := ret[0].(*storage.TriggerReportResult)
	return ret0
}

// StageAndReportAll indicates an expected call of StageAndReportAll.
func (mr *MockStorageMockRecorder) StageAndReportAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StageAndReportAll", reflect.TypeOf((*MockStorage)(nil).StageAndReportAll), arg0)
}

// StageAndReportMany mocks base method.
func (m *MockStorage) StageAndReportMany(arg0 context.Context, arg1 []types.ChunkID) *storage.TriggerReportResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StageAndReportMany", arg0, arg1)
	ret0, _ := ret[0].(*storage.TriggerReportResult)
	return ret0
}

// StageAndReportMany indicates an expected call of StageAndReportMany.
func (mr *MockStorageMockRecorder) StageAndReportMany(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StageAndReportMany", reflect.TypeOf((*MockStorage)(nil).StageAndReportMany), arg0, arg1)
}

// MockHeartbeat is a mock of Heartbeat interface.
type MockHeartbeat struct {
	ctrl     *gomock.Controller
	recorder *MockHeartbeatMockRecorder
	isgomock struct{}
}

// MockHeartbeatMockRecorder is the mock recorder for MockHeartbeat.
type MockHeartbeatMockRecorder struct {
	mock *MockHeartbeat
}

// NewMockHeartbeat creates a new mock instance.
func NewMockHeartbeat(ctrl *gomock.Controller) *MockHeartbeat {
	mock := &MockHeartbeat{ctrl: ctrl}
	mock.recorder = &MockHeartbeatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeartbeat) EXPECT() *MockHeartbeatMockRecorder {
	return m.recorder
}

// IsPaused mocks base method.
func (m *MockHeartbeat) IsPaused() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPaused")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPaused indicates an expected call of IsPaused.
func (mr *MockHeartbeatMockRecorder) IsPaused() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPaused", reflect.TypeOf((*MockHeartbeat)(nil).IsPaused))
}

// Pause mocks base method.
func (m *MockHeartbeat) Pause() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockHeartbeatMockRecorder) Pause() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockHeartbeat)(nil).Pause))
}

// Resume mocks base method.
func (m *MockHeartbeat) Resume() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockHeartbeatMockRecorder) Resume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockHeartbeat)(nil).Resume))
}
