apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storage.serviceName }}
  namespace: {{ .Values.namespace.name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: dos-storage
  ports:
    - name: grpc
      port: {{ .Values.storage.apiPort }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.storage.metricsPort }}
      targetPort: metrics

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
  namespace: {{ .Values.namespace.name }}
spec:
  serviceName: {{ .Values.storage.serviceName }}
  replicas: {{ .Values.storage.replicas }}
  selector:
    matchLabels:
      app: dos-storage
  template:
    metadata:
      labels:
        app: dos-storage
    spec:
      containers:
        - name: storage
          image: {{ .Values.storage.image | quote }}
          imagePullPolicy: Never
          ports:
            - name: grpc
              containerPort: {{ .Values.storage.apiPort }}
            - name: metrics
              containerPort: {{ .Values.storage.metricsPort }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TRANSPORT__ADVERTISE_ADDR
              value: "$(POD_NAME).{{ .Values.storage.serviceName }}:{{ .Values.storage.apiPort }}"
            - name: MASTER__PEERS
              value: {{ include "dos.masterPeers" . | quote }}
            - name: TRANSPORT__FRAME_SIZE
              valueFrom:
                configMapKeyRef:
                  name: dos-config
                  key: FRAME_SIZE
            - name: TRANSPORT__RPC_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: dos-config
                  key: RPC_TIMEOUT
            - name: SERVICE__HEARTBEAT_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: dos-config
                  key: HEARTBEAT_INTERVAL
            - name: SERVICE__REPORT_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: dos-config
                  key: REPORT_INTERVAL
            - name: SERVICE__MAX_PARALLEL_HEAVY_OPS
              valueFrom:
                configMapKeyRef:
                  name: dos-config
                  key: MAX_PARALLEL_HEAVY_OPS
