// Code generated by MockGen. DO NOT EDIT.
// Source: facade.go
//
// Generated by this command:
//
//	mockgen -source=facade.go -destination=facade_mocks_test.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	types "dos/internal/common/types"
	master "dos/internal/services/master"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientFacadeConfig is a mock of ClientFacadeConfig interface.
type MockClientFacadeConfig struct {
	ctrl     *gomock.Controller
	recorder *MockClientFacadeConfigMockRecorder
	isgomock struct{}
}

// MockClientFacadeConfigMockRecorder is the mock recorder for MockClientFacadeConfig.
type MockClientFacadeConfigMockRecorder struct {
	mock *MockClientFacadeConfig
}

// NewMockClientFacadeConfig creates a new mock instance.
func NewMockClientFacadeConfig(ctrl *gomock.Controller) *MockClientFacadeConfig {
	mock := &MockClientFacadeConfig{ctrl: ctrl}
	mock.recorder = &MockClientFacadeConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFacadeConfig) EXPECT() *MockClientFacadeConfigMockRecorder {
	return m.recorder
}

// ReplicationCount mocks base method.
func (m *MockClientFacadeConfig) ReplicationCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicationCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// ReplicationCount indicates an expected call of ReplicationCount.
func (mr *MockClientFacadeConfigMockRecorder) ReplicationCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicationCount", reflect.TypeOf((*MockClientFacadeConfig)(nil).ReplicationCount))
}

// MockReplicationScheduler is a mock of ReplicationScheduler interface.
type MockReplicationScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockReplicationSchedulerMockRecorder
	isgomock struct{}
}

// MockReplicationSchedulerMockRecorder is the mock recorder for MockReplicationScheduler.
type MockReplicationSchedulerMockRecorder struct {
	mock *MockReplicationScheduler
}

// NewMockReplicationScheduler creates a new mock instance.
func NewMockReplicationScheduler(ctrl *gomock.Controller) *MockReplicationScheduler {
	mock := &MockReplicationScheduler{ctrl: ctrl}
	mock.recorder = &MockReplicationSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplicationScheduler) EXPECT() *MockReplicationSchedulerMockRecorder {
	return m.recorder
}

// Schedule mocks base method.
func (m *MockReplicationScheduler) Schedule(arg0 context.Context, arg1 types.ChunkID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Schedule", arg0, arg1)
}

// Schedule indicates an expected call of Schedule.
func (mr *MockReplicationSchedulerMockRecorder) Schedule(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockReplicationScheduler)(nil).Schedule), arg0, arg1)
}

// MockCatalog is a mock of Catalog interface.
type MockCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogMockRecorder
	isgomock struct{}
}

// MockCatalogMockRecorder is the mock recorder for MockCatalog.
type MockCatalogMockRecorder struct {
	mock *MockCatalog
}

// NewMockCatalog creates a new mock instance.
func NewMockCatalog(ctrl *gomock.Controller) *MockCatalog {
	mock := &MockCatalog{ctrl: ctrl}
	mock.recorder = &MockCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalog) EXPECT() *MockCatalogMockRecorder {
	return m.recorder
}

// AddChunk mocks base method.
func (m *MockCatalog) AddChunk(arg0 context.Context, arg1 types.ObjectSlot, arg2 int64) (types.ChunkID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChunk", arg0, arg1, arg2)
	ret0, _ := ret[0].(types.ChunkID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddChunk indicates an expected call of AddChunk.
func (mr *MockCatalogMockRecorder) AddChunk(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChunk", reflect.TypeOf((*MockCatalog)(nil).AddChunk), arg0, arg1, arg2)
}

// CreateObject mocks base method.
func (m *MockCatalog) CreateObject(arg0 context.Context, arg1 types.ObjectID, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObject", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateObject indicates an expected call of CreateObject.
func (mr *MockCatalogMockRecorder) CreateObject(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObject", reflect.TypeOf((*MockCatalog)(nil).CreateObject), arg0, arg1, arg2)
}

// ExistsChunk mocks base method.
func (m *MockCatalog) ExistsChunk(arg0 context.Context, arg1 types.ObjectSlot) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsChunk", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsChunk indicates an expected call of ExistsChunk.
func (mr *MockCatalogMockRecorder) ExistsChunk(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsChunk", reflect.TypeOf((*MockCatalog)(nil).ExistsChunk), arg0, arg1)
}

// GetChunk mocks base method.
func (m *MockCatalog) GetChunk(arg0 context.Context, arg1 types.ChunkID) (master.Chunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunk", arg0, arg1)
	ret0, _ := ret[0].(master.Chunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunk indicates an expected call of GetChunk.
func (mr *MockCatalogMockRecorder) GetChunk(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunk", reflect.TypeOf((*MockCatalog)(nil).GetChunk), arg0, arg1)
}

// GetChunkID mocks base method.
func (m *MockCatalog) GetChunkID(arg0 context.Context, arg1 types.ObjectSlot) (types.ChunkID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunkID", arg0, arg1)
	ret0, _ := ret[0].(types.ChunkID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunkID indicates an expected call of GetChunkID.
func (mr *MockCatalogMockRecorder) GetChunkID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunkID", reflect.TypeOf((*MockCatalog)(nil).GetChunkID), arg0, arg1)
}

// GetObject mocks base method.
func (m *MockCatalog) GetObject(arg0 context.Context, arg1 types.ObjectID) (master.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", arg0, arg1)
	ret0, _ := ret[0].(master.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockCatalogMockRecorder) GetObject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockCatalog)(nil).GetObject), arg0, arg1)
}

// GetObjectChunks mocks base method.
func (m *MockCatalog) GetObjectChunks(arg0 context.Context, arg1 types.ObjectID) ([]types.ChunkID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectChunks", arg0, arg1)
	ret0, _ := ret[0].([]types.ChunkID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectChunks indicates an expected call of GetObjectChunks.
func (mr *MockCatalogMockRecorder) GetObjectChunks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectChunks", reflect.TypeOf((*MockCatalog)(nil).GetObjectChunks), arg0, arg1)
}

// GetReplication mocks base method.
func (m *MockCatalog) GetReplication(arg0 context.Context, arg1 types.ObjectID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplication", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplication indicates an expected call of GetReplication.
func (mr *MockCatalogMockRecorder) GetReplication(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplication", reflect.TypeOf((*MockCatalog)(nil).GetReplication), arg0, arg1)
}

// SetReplication mocks base method.
func (m *MockCatalog) SetReplication(arg0 context.Context, arg1 types.ObjectID, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReplication", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReplication indicates an expected call of SetReplication.
func (mr *MockCatalogMockRecorder) SetReplication(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReplication", reflect.TypeOf((*MockCatalog)(nil).SetReplication), arg0, arg1, arg2)
}

// MockPlacement is a mock of Placement interface.
type MockPlacement struct {
	ctrl     *gomock.Controller
	recorder *MockPlacementMockRecorder
	isgomock struct{}
}

// MockPlacementMockRecorder is the mock recorder for MockPlacement.
type MockPlacementMockRecorder struct {
	mock *MockPlacement
}

// NewMockPlacement creates a new mock instance.
func NewMockPlacement(ctrl *gomock.Controller) *MockPlacement {
	mock := &MockPlacement{ctrl: ctrl}
	mock.recorder = &MockPlacementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlacement) EXPECT() *MockPlacementMockRecorder {
	return m.recorder
}

// GetCandidates mocks base method.
func (m *MockPlacement) GetCandidates(arg0 context.Context, arg1 master.CandidateNodesQuery) ([]types.NodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandidates", arg0, arg1)
	ret0, _ := ret[0].([]types.NodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCandidates indicates an expected call of GetCandidates.
func (mr *MockPlacementMockRecorder) GetCandidates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandidates", reflect.TypeOf((*MockPlacement)(nil).GetCandidates), arg0, arg1)
}

// GetChunkNodes mocks base method.
func (m *MockPlacement) GetChunkNodes(arg0 context.Context, arg1 types.ChunkID) ([]types.NodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunkNodes", arg0, arg1)
	ret0, _ := ret[0].([]types.NodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunkNodes indicates an expected call of GetChunkNodes.
func (mr *MockPlacementMockRecorder) GetChunkNodes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunkNodes", reflect.TypeOf((*MockPlacement)(nil).GetChunkNodes), arg0, arg1)
}

// MockLifecycle is a mock of Lifecycle interface.
type MockLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleMockRecorder
	isgomock struct{}
}

// MockLifecycleMockRecorder is the mock recorder for MockLifecycle.
type MockLifecycleMockRecorder struct {
	mock *MockLifecycle
}

// NewMockLifecycle creates a new mock instance.
func NewMockLifecycle(ctrl *gomock.Controller) *MockLifecycle {
	mock := &MockLifecycle{ctrl: ctrl}
	mock.recorder = &MockLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycle) EXPECT() *MockLifecycleMockRecorder {
	return m.recorder
}

// GetNodeCount mocks base method.
func (m *MockLifecycle) GetNodeCount(arg0 context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeCount", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetNodeCount indicates an expected call of GetNodeCount.
func (mr *MockLifecycleMockRecorder) GetNodeCount(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeCount", reflect.TypeOf((*MockLifecycle)(nil).GetNodeCount), arg0)
}

// ListNodes mocks base method.
func (m *MockLifecycle) ListNodes(arg0 context.Context) []types.NodeInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", arg0)
	ret0, _ := ret[0].([]types.NodeInfo)
	return ret0
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockLifecycleMockRecorder) ListNodes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockLifecycle)(nil).ListNodes), arg0)
}

// Register mocks base method.
func (m *MockLifecycle) Register(arg0 context.Context, arg1 string) (types.NodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(types.NodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockLifecycleMockRecorder) Register(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockLifecycle)(nil).Register), arg0, arg1)
}
