logger:
  level: debug
  component: storage 

listen:
  host: "0.0.0.0"
  port: 10001

store:
  max_storage: 10GB
  root_dir: ./storage_data

transport:
  advertise_addr: localhost:10001
  master_addr: localhost:10000
  frame_size: 1MB

service:
  heartbeat_interval: 15s
  registration_timeout: 1m
  replication_timeout: 30s

  report_interval: 15s
  report_queue_capacity: 10

  max_parallel_heavy_ops: 1
