logger:
  level: debug
  component: storage 

store:
  max_storage: 10GB
  root_dir: ./storage_data

master:
  api_port: 10000
  peers:
    - master-0
    - master-1
    - master-2

transport:
  advertise_addr: localhost:10001
  frame_size: 1MB
  rpc_timeout: 10s

metrics:
  scrape_port: 9100
  scrape_path: /metrics
  namespace: dos 

service:
  heartbeat_interval: 1s
  registration_timeout: 10s
  replication_timeout: 10s

  report_interval: 1s
  report_queue_capacity: 100

  max_parallel_heavy_ops: 2
