// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/mocks.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	types "dos/internal/common/types"
	io "dos/internal/services/client/io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectAssembler is a mock of ObjectAssembler interface.
type MockObjectAssembler struct {
	ctrl     *gomock.Controller
	recorder *MockObjectAssemblerMockRecorder
	isgomock struct{}
}

// MockObjectAssemblerMockRecorder is the mock recorder for MockObjectAssembler.
type MockObjectAssemblerMockRecorder struct {
	mock *MockObjectAssembler
}

// NewMockObjectAssembler creates a new mock instance.
func NewMockObjectAssembler(ctrl *gomock.Controller) *MockObjectAssembler {
	mock := &MockObjectAssembler{ctrl: ctrl}
	mock.recorder = &MockObjectAssemblerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectAssembler) EXPECT() *MockObjectAssemblerMockRecorder {
	return m.recorder
}

// NewSink mocks base method.
func (m *MockObjectAssembler) NewSink(arg0 []types.ChunkPlacement) (io.ObjectSink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSink", arg0)
	ret0, _ := ret[0].(io.ObjectSink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSink indicates an expected call of NewSink.
func (mr *MockObjectAssemblerMockRecorder) NewSink(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSink", reflect.TypeOf((*MockObjectAssembler)(nil).NewSink), arg0)
}

// MockObjectSink is a mock of ObjectSink interface.
type MockObjectSink struct {
	ctrl     *gomock.Controller
	recorder *MockObjectSinkMockRecorder
	isgomock struct{}
}

// MockObjectSinkMockRecorder is the mock recorder for MockObjectSink.
type MockObjectSinkMockRecorder struct {
	mock *MockObjectSink
}

// NewMockObjectSink creates a new mock instance.
func NewMockObjectSink(ctrl *gomock.Controller) *MockObjectSink {
	mock := &MockObjectSink{ctrl: ctrl}
	mock.recorder = &MockObjectSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectSink) EXPECT() *MockObjectSinkMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockObjectSink) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockObjectSinkMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObjectSink)(nil).Close))
}

// WriteChunk mocks base method.
func (m *MockObjectSink) WriteChunk(arg0 types.ChunkKey, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteChunk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteChunk indicates an expected call of WriteChunk.
func (mr *MockObjectSinkMockRecorder) WriteChunk(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteChunk", reflect.TypeOf((*MockObjectSink)(nil).WriteChunk), arg0, arg1)
}
