// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/mocks.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	digest "dos/internal/common/digest"
	types "dos/internal/common/types"
	master "dos/internal/services/master"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageNodePlacement is a mock of StorageNodePlacement interface.
type MockStorageNodePlacement struct {
	ctrl     *gomock.Controller
	recorder *MockStorageNodePlacementMockRecorder
	isgomock struct{}
}

// MockStorageNodePlacementMockRecorder is the mock recorder for MockStorageNodePlacement.
type MockStorageNodePlacementMockRecorder struct {
	mock *MockStorageNodePlacement
}

// NewMockStorageNodePlacement creates a new mock instance.
func NewMockStorageNodePlacement(ctrl *gomock.Controller) *MockStorageNodePlacement {
	mock := &MockStorageNodePlacement{ctrl: ctrl}
	mock.recorder = &MockStorageNodePlacementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageNodePlacement) EXPECT() *MockStorageNodePlacementMockRecorder {
	return m.recorder
}

// GetCandidates mocks base method.
func (m *MockStorageNodePlacement) GetCandidates(arg0 context.Context, arg1 master.CandidateNodesQuery) ([]types.NodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandidates", arg0, arg1)
	ret0, _ := ret[0].([]types.NodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCandidates indicates an expected call of GetCandidates.
func (mr *MockStorageNodePlacementMockRecorder) GetCandidates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandidates", reflect.TypeOf((*MockStorageNodePlacement)(nil).GetCandidates), arg0, arg1)
}

// GetChunkNodes mocks base method.
func (m *MockStorageNodePlacement) GetChunkNodes(arg0 context.Context, arg1 types.ChunkID) ([]types.NodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunkNodes", arg0, arg1)
	ret0, _ := ret[0].([]types.NodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunkNodes indicates an expected call of GetChunkNodes.
func (mr *MockStorageNodePlacementMockRecorder) GetChunkNodes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunkNodes", reflect.TypeOf((*MockStorageNodePlacement)(nil).GetChunkNodes), arg0, arg1)
}

// MockChunkRepo is a mock of ChunkRepo interface.
type MockChunkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockChunkRepoMockRecorder
	isgomock struct{}
}

// MockChunkRepoMockRecorder is the mock recorder for MockChunkRepo.
type MockChunkRepoMockRecorder struct {
	mock *MockChunkRepo
}

// NewMockChunkRepo creates a new mock instance.
func NewMockChunkRepo(ctrl *gomock.Controller) *MockChunkRepo {
	mock := &MockChunkRepo{ctrl: ctrl}
	mock.recorder = &MockChunkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkRepo) EXPECT() *MockChunkRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChunkRepo) Create(arg0 context.Context, arg1 types.ChunkID, arg2 types.ObjectSlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockChunkRepoMockRecorder) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChunkRepo)(nil).Create), arg0, arg1, arg2)
}

// DecReplicaCount mocks base method.
func (m *MockChunkRepo) DecReplicaCount(arg0 context.Context, arg1 types.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecReplicaCount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecReplicaCount indicates an expected call of DecReplicaCount.
func (mr *MockChunkRepoMockRecorder) DecReplicaCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecReplicaCount", reflect.TypeOf((*MockChunkRepo)(nil).DecReplicaCount), arg0, arg1)
}

// Delete mocks base method.
func (m *MockChunkRepo) Delete(arg0 context.Context, arg1 types.ChunkID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockChunkRepoMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChunkRepo)(nil).Delete), arg0, arg1)
}

// Drop mocks base method.
func (m *MockChunkRepo) Drop(arg0 context.Context, arg1 types.ChunkID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Drop", arg0, arg1)
}

// Drop indicates an expected call of Drop.
func (mr *MockChunkRepoMockRecorder) Drop(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockChunkRepo)(nil).Drop), arg0, arg1)
}

// Exists mocks base method.
func (m *MockChunkRepo) Exists(arg0 context.Context, arg1 types.ChunkID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockChunkRepoMockRecorder) Exists(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockChunkRepo)(nil).Exists), arg0, arg1)
}

// ForEach mocks base method.
func (m *MockChunkRepo) ForEach(arg0 context.Context, arg1 func(master.Chunk)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForEach", arg0, arg1)
}

// ForEach indicates an expected call of ForEach.
func (mr *MockChunkRepoMockRecorder) ForEach(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForEach", reflect.TypeOf((*MockChunkRepo)(nil).ForEach), arg0, arg1)
}

// Get mocks base method.
func (m *MockChunkRepo) Get(arg0 context.Context, arg1 types.ChunkID) (master.Chunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(master.Chunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockChunkRepoMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockChunkRepo)(nil).Get), arg0, arg1)
}

// GetDigest mocks base method.
func (m *MockChunkRepo) GetDigest(arg0 context.Context, arg1 types.ChunkID) (digest.Digest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDigest", arg0, arg1)
	ret0, _ := ret[0].(digest.Digest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDigest indicates an expected call of GetDigest.
func (mr *MockChunkRepoMockRecorder) GetDigest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDigest", reflect.TypeOf((*MockChunkRepo)(nil).GetDigest), arg0, arg1)
}

// IncReplicaCount mocks base method.
func (m *MockChunkRepo) IncReplicaCount(arg0 context.Context, arg1 types.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncReplicaCount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncReplicaCount indicates an expected call of IncReplicaCount.
func (mr *MockChunkRepoMockRecorder) IncReplicaCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncReplicaCount", reflect.TypeOf((*MockChunkRepo)(nil).IncReplicaCount), arg0, arg1)
}

// List mocks base method.
func (m *MockChunkRepo) List(arg0 context.Context) []master.Chunk {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]master.Chunk)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockChunkRepoMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockChunkRepo)(nil).List), arg0)
}

// NewChunkID mocks base method.
func (m *MockChunkRepo) NewChunkID() types.ChunkID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChunkID")
	ret0, _ := ret[0].(types.ChunkID)
	return ret0
}

// NewChunkID indicates an expected call of NewChunkID.
func (mr *MockChunkRepoMockRecorder) NewChunkID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChunkID", reflect.TypeOf((*MockChunkRepo)(nil).NewChunkID))
}

// SetDigest mocks base method.
func (m *MockChunkRepo) SetDigest(arg0 context.Context, arg1 types.ChunkID, arg2 digest.Digest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDigest", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDigest indicates an expected call of SetDigest.
func (mr *MockChunkRepoMockRecorder) SetDigest(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDigest", reflect.TypeOf((*MockChunkRepo)(nil).SetDigest), arg0, arg1, arg2)
}

// Touch mocks base method.
func (m *MockChunkRepo) Touch(arg0 context.Context, arg1 types.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockChunkRepoMockRecorder) Touch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockChunkRepo)(nil).Touch), arg0, arg1)
}

// MockNodeRegistry is a mock of NodeRegistry interface.
type MockNodeRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockNodeRegistryMockRecorder
	isgomock struct{}
}

// MockNodeRegistryMockRecorder is the mock recorder for MockNodeRegistry.
type MockNodeRegistryMockRecorder struct {
	mock *MockNodeRegistry
}

// NewMockNodeRegistry creates a new mock instance.
func NewMockNodeRegistry(ctrl *gomock.Controller) *MockNodeRegistry {
	mock := &MockNodeRegistry{ctrl: ctrl}
	mock.recorder = &MockNodeRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeRegistry) EXPECT() *MockNodeRegistryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockNodeRegistry) Count(arg0 context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockNodeRegistryMockRecorder) Count(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockNodeRegistry)(nil).Count), arg0)
}

// Find mocks base method.
func (m *MockNodeRegistry) Find(arg0 context.Context, arg1 master.NodeQuery) []master.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].([]master.Node)
	return ret0
}

// Find indicates an expected call of Find.
func (mr *MockNodeRegistryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockNodeRegistry)(nil).Find), arg0, arg1)
}

// Get mocks base method.
func (m *MockNodeRegistry) Get(arg0 context.Context, arg1 types.NodeID) (master.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(master.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNodeRegistryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNodeRegistry)(nil).Get), arg0, arg1)
}

// GetInactive mocks base method.
func (m *MockNodeRegistry) GetInactive(arg0 context.Context, arg1 time.Time) []types.NodeID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInactive", arg0, arg1)
	ret0, _ := ret[0].([]types.NodeID)
	return ret0
}

// GetInactive indicates an expected call of GetInactive.
func (mr *MockNodeRegistryMockRecorder) GetInactive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInactive", reflect.TypeOf((*MockNodeRegistry)(nil).GetInactive), arg0, arg1)
}

// GetMany mocks base method.
func (m *MockNodeRegistry) GetMany(arg0 context.Context, arg1 ...types.NodeID) []master.Node {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMany", varargs...)
	ret0, _ := ret[0].([]master.Node)
	return ret0
}

// GetMany indicates an expected call of GetMany.
func (mr *MockNodeRegistryMockRecorder) GetMany(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMany", reflect.TypeOf((*MockNodeRegistry)(nil).GetMany), varargs...)
}

// Register mocks base method.
func (m *MockNodeRegistry) Register(arg0 context.Context, arg1 string) (types.NodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(types.NodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockNodeRegistryMockRecorder) Register(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockNodeRegistry)(nil).Register), arg0, arg1)
}

// Unregister mocks base method.
func (m *MockNodeRegistry) Unregister(arg0 context.Context, arg1 types.NodeID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", arg0, arg1)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockNodeRegistryMockRecorder) Unregister(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockNodeRegistry)(nil).Unregister), arg0, arg1)
}

// UpdateStats mocks base method.
func (m *MockNodeRegistry) UpdateStats(arg0 context.Context, arg1 types.NodeID, arg2 types.NodeStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStats", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStats indicates an expected call of UpdateStats.
func (mr *MockNodeRegistryMockRecorder) UpdateStats(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStats", reflect.TypeOf((*MockNodeRegistry)(nil).UpdateStats), arg0, arg1, arg2)
}

// MockChunkNodeIndex is a mock of ChunkNodeIndex interface.
type MockChunkNodeIndex struct {
	ctrl     *gomock.Controller
	recorder *MockChunkNodeIndexMockRecorder
	isgomock struct{}
}

// MockChunkNodeIndexMockRecorder is the mock recorder for MockChunkNodeIndex.
type MockChunkNodeIndexMockRecorder struct {
	mock *MockChunkNodeIndex
}

// NewMockChunkNodeIndex creates a new mock instance.
func NewMockChunkNodeIndex(ctrl *gomock.Controller) *MockChunkNodeIndex {
	mock := &MockChunkNodeIndex{ctrl: ctrl}
	mock.recorder = &MockChunkNodeIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkNodeIndex) EXPECT() *MockChunkNodeIndexMockRecorder {
	return m.recorder
}

// AttachChunk mocks base method.
func (m *MockChunkNodeIndex) AttachChunk(ctx context.Context, nodeID types.NodeID, chunkID types.ChunkID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachChunk", ctx, nodeID, chunkID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AttachChunk indicates an expected call of AttachChunk.
func (mr *MockChunkNodeIndexMockRecorder) AttachChunk(ctx, nodeID, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachChunk", reflect.TypeOf((*MockChunkNodeIndex)(nil).AttachChunk), ctx, nodeID, chunkID)
}

// DetachChunk mocks base method.
func (m *MockChunkNodeIndex) DetachChunk(ctx context.Context, nodeID types.NodeID, chunkID types.ChunkID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachChunk", ctx, nodeID, chunkID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DetachChunk indicates an expected call of DetachChunk.
func (mr *MockChunkNodeIndexMockRecorder) DetachChunk(ctx, nodeID, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachChunk", reflect.TypeOf((*MockChunkNodeIndex)(nil).DetachChunk), ctx, nodeID, chunkID)
}

// DetachNode mocks base method.
func (m *MockChunkNodeIndex) DetachNode(ctx context.Context, nodeID types.NodeID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DetachNode", ctx, nodeID)
}

// DetachNode indicates an expected call of DetachNode.
func (mr *MockChunkNodeIndexMockRecorder) DetachNode(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachNode", reflect.TypeOf((*MockChunkNodeIndex)(nil).DetachNode), ctx, nodeID)
}

// GetChunkNodes mocks base method.
func (m *MockChunkNodeIndex) GetChunkNodes(ctx context.Context, chunkID types.ChunkID) []types.NodeID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunkNodes", ctx, chunkID)
	ret0, _ := ret[0].([]types.NodeID)
	return ret0
}

// GetChunkNodes indicates an expected call of GetChunkNodes.
func (mr *MockChunkNodeIndexMockRecorder) GetChunkNodes(ctx, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunkNodes", reflect.TypeOf((*MockChunkNodeIndex)(nil).GetChunkNodes), ctx, chunkID)
}

// GetNodeChunks mocks base method.
func (m *MockChunkNodeIndex) GetNodeChunks(ctx context.Context, nodeID types.NodeID) []types.ChunkID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeChunks", ctx, nodeID)
	ret0, _ := ret[0].([]types.ChunkID)
	return ret0
}

// GetNodeChunks indicates an expected call of GetNodeChunks.
func (mr *MockChunkNodeIndexMockRecorder) GetNodeChunks(ctx, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeChunks", reflect.TypeOf((*MockChunkNodeIndex)(nil).GetNodeChunks), ctx, nodeID)
}

// MockPlacementPolicy is a mock of PlacementPolicy interface.
type MockPlacementPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockPlacementPolicyMockRecorder
	isgomock struct{}
}

// MockPlacementPolicyMockRecorder is the mock recorder for MockPlacementPolicy.
type MockPlacementPolicyMockRecorder struct {
	mock *MockPlacementPolicy
}

// NewMockPlacementPolicy creates a new mock instance.
func NewMockPlacementPolicy(ctrl *gomock.Controller) *MockPlacementPolicy {
	mock := &MockPlacementPolicy{ctrl: ctrl}
	mock.recorder = &MockPlacementPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlacementPolicy) EXPECT() *MockPlacementPolicyMockRecorder {
	return m.recorder
}

// Select mocks base method.
func (m *MockPlacementPolicy) Select(nodes []master.Node, n int) []master.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", nodes, n)
	ret0, _ := ret[0].([]master.Node)
	return ret0
}

// Select indicates an expected call of Select.
func (mr *MockPlacementPolicyMockRecorder) Select(nodes, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockPlacementPolicy)(nil).Select), nodes, n)
}

// MockReplicaScheduler is a mock of ReplicaScheduler interface.
type MockReplicaScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockReplicaSchedulerMockRecorder
	isgomock struct{}
}

// MockReplicaSchedulerMockRecorder is the mock recorder for MockReplicaScheduler.
type MockReplicaSchedulerMockRecorder struct {
	mock *MockReplicaScheduler
}

// NewMockReplicaScheduler creates a new mock instance.
func NewMockReplicaScheduler(ctrl *gomock.Controller) *MockReplicaScheduler {
	mock := &MockReplicaScheduler{ctrl: ctrl}
	mock.recorder = &MockReplicaSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplicaScheduler) EXPECT() *MockReplicaSchedulerMockRecorder {
	return m.recorder
}

// Schedule mocks base method.
func (m *MockReplicaScheduler) Schedule(arg0 context.Context, arg1 types.ChunkID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Schedule", arg0, arg1)
}

// Schedule indicates an expected call of Schedule.
func (mr *MockReplicaSchedulerMockRecorder) Schedule(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockReplicaScheduler)(nil).Schedule), arg0, arg1)
}

// MockMasterState is a mock of MasterState interface.
type MockMasterState struct {
	ctrl     *gomock.Controller
	recorder *MockMasterStateMockRecorder
	isgomock struct{}
}

// MockMasterStateMockRecorder is the mock recorder for MockMasterState.
type MockMasterStateMockRecorder struct {
	mock *MockMasterState
}

// NewMockMasterState creates a new mock instance.
func NewMockMasterState(ctrl *gomock.Controller) *MockMasterState {
	mock := &MockMasterState{ctrl: ctrl}
	mock.recorder = &MockMasterStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterState) EXPECT() *MockMasterStateMockRecorder {
	return m.recorder
}

// GetActiveMaster mocks base method.
func (m *MockMasterState) GetActiveMaster(arg0 context.Context) (types.MasterRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMaster", arg0)
	ret0, _ := ret[0].(types.MasterRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMaster indicates an expected call of GetActiveMaster.
func (mr *MockMasterStateMockRecorder) GetActiveMaster(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMaster", reflect.TypeOf((*MockMasterState)(nil).GetActiveMaster), arg0)
}

// IsActiveMaster mocks base method.
func (m *MockMasterState) IsActiveMaster() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActiveMaster")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsActiveMaster indicates an expected call of IsActiveMaster.
func (mr *MockMasterStateMockRecorder) IsActiveMaster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActiveMaster", reflect.TypeOf((*MockMasterState)(nil).IsActiveMaster))
}

// TransferLeadership mocks base method.
func (m *MockMasterState) TransferLeadership(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferLeadership", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferLeadership indicates an expected call of TransferLeadership.
func (mr *MockMasterStateMockRecorder) TransferLeadership(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferLeadership", reflect.TypeOf((*MockMasterState)(nil).TransferLeadership), arg0)
}

// WatchState mocks base method.
func (m *MockMasterState) WatchState(arg0 context.Context, arg1 func(context.Context)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatchState", arg0, arg1)
}

// WatchState indicates an expected call of WatchState.
func (mr *MockMasterStateMockRecorder) WatchState(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchState", reflect.TypeOf((*MockMasterState)(nil).WatchState), arg0, arg1)
}

// MockObjectReader is a mock of ObjectReader interface.
type MockObjectReader struct {
	ctrl     *gomock.Controller
	recorder *MockObjectReaderMockRecorder
	isgomock struct{}
}

// MockObjectReaderMockRecorder is the mock recorder for MockObjectReader.
type MockObjectReaderMockRecorder struct {
	mock *MockObjectReader
}

// NewMockObjectReader creates a new mock instance.
func NewMockObjectReader(ctrl *gomock.Controller) *MockObjectReader {
	mock := &MockObjectReader{ctrl: ctrl}
	mock.recorder = &MockObjectReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectReader) EXPECT() *MockObjectReaderMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockObjectReader) Exists(ctx context.Context, objectID types.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, objectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockObjectReaderMockRecorder) Exists(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockObjectReader)(nil).Exists), ctx, objectID)
}

// ExistsChunk mocks base method.
func (m *MockObjectReader) ExistsChunk(ctx context.Context, slot types.ObjectSlot) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsChunk", ctx, slot)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsChunk indicates an expected call of ExistsChunk.
func (mr *MockObjectReaderMockRecorder) ExistsChunk(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsChunk", reflect.TypeOf((*MockObjectReader)(nil).ExistsChunk), ctx, slot)
}

// Get mocks base method.
func (m *MockObjectReader) Get(ctx context.Context, objectID types.ObjectID) (master.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, objectID)
	ret0, _ := ret[0].(master.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObjectReaderMockRecorder) Get(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectReader)(nil).Get), ctx, objectID)
}

// GetChunk mocks base method.
func (m *MockObjectReader) GetChunk(ctx context.Context, slot types.ObjectSlot) (types.ChunkID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunk", ctx, slot)
	ret0, _ := ret[0].(types.ChunkID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunk indicates an expected call of GetChunk.
func (mr *MockObjectReaderMockRecorder) GetChunk(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunk", reflect.TypeOf((*MockObjectReader)(nil).GetChunk), ctx, slot)
}

// GetReplication mocks base method.
func (m *MockObjectReader) GetReplication(ctx context.Context, objectID types.ObjectID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplication", ctx, objectID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplication indicates an expected call of GetReplication.
func (mr *MockObjectReaderMockRecorder) GetReplication(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplication", reflect.TypeOf((*MockObjectReader)(nil).GetReplication), ctx, objectID)
}

// List mocks base method.
func (m *MockObjectReader) List(ctx context.Context) []master.Object {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]master.Object)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockObjectReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockObjectReader)(nil).List), ctx)
}

// MockObjectWriter is a mock of ObjectWriter interface.
type MockObjectWriter struct {
	ctrl     *gomock.Controller
	recorder *MockObjectWriterMockRecorder
	isgomock struct{}
}

// MockObjectWriterMockRecorder is the mock recorder for MockObjectWriter.
type MockObjectWriterMockRecorder struct {
	mock *MockObjectWriter
}

// NewMockObjectWriter creates a new mock instance.
func NewMockObjectWriter(ctrl *gomock.Controller) *MockObjectWriter {
	mock := &MockObjectWriter{ctrl: ctrl}
	mock.recorder = &MockObjectWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectWriter) EXPECT() *MockObjectWriterMockRecorder {
	return m.recorder
}

// AddChunk mocks base method.
func (m *MockObjectWriter) AddChunk(arg0 context.Context, arg1 types.ObjectSlot, arg2 types.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChunk", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChunk indicates an expected call of AddChunk.
func (mr *MockObjectWriterMockRecorder) AddChunk(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChunk", reflect.TypeOf((*MockObjectWriter)(nil).AddChunk), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockObjectWriter) Create(arg0 context.Context, arg1 types.ObjectID, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockObjectWriterMockRecorder) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockObjectWriter)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockObjectWriter) Delete(arg0 context.Context, arg1 types.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectWriterMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectWriter)(nil).Delete), arg0, arg1)
}

// DeleteChunk mocks base method.
func (m *MockObjectWriter) DeleteChunk(arg0 context.Context, arg1 types.ObjectSlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChunk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChunk indicates an expected call of DeleteChunk.
func (mr *MockObjectWriterMockRecorder) DeleteChunk(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChunk", reflect.TypeOf((*MockObjectWriter)(nil).DeleteChunk), arg0, arg1)
}

// SetReplication mocks base method.
func (m *MockObjectWriter) SetReplication(arg0 context.Context, arg1 types.ObjectID, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReplication", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReplication indicates an expected call of SetReplication.
func (mr *MockObjectWriterMockRecorder) SetReplication(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReplication", reflect.TypeOf((*MockObjectWriter)(nil).SetReplication), arg0, arg1, arg2)
}

// MockObjectRW is a mock of ObjectRW interface.
type MockObjectRW struct {
	ctrl     *gomock.Controller
	recorder *MockObjectRWMockRecorder
	isgomock struct{}
}

// MockObjectRWMockRecorder is the mock recorder for MockObjectRW.
type MockObjectRWMockRecorder struct {
	mock *MockObjectRW
}

// NewMockObjectRW creates a new mock instance.
func NewMockObjectRW(ctrl *gomock.Controller) *MockObjectRW {
	mock := &MockObjectRW{ctrl: ctrl}
	mock.recorder = &MockObjectRWMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectRW) EXPECT() *MockObjectRWMockRecorder {
	return m.recorder
}

// AddChunk mocks base method.
func (m *MockObjectRW) AddChunk(arg0 context.Context, arg1 types.ObjectSlot, arg2 types.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChunk", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChunk indicates an expected call of AddChunk.
func (mr *MockObjectRWMockRecorder) AddChunk(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChunk", reflect.TypeOf((*MockObjectRW)(nil).AddChunk), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockObjectRW) Create(arg0 context.Context, arg1 types.ObjectID, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockObjectRWMockRecorder) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockObjectRW)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockObjectRW) Delete(arg0 context.Context, arg1 types.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectRWMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectRW)(nil).Delete), arg0, arg1)
}

// DeleteChunk mocks base method.
func (m *MockObjectRW) DeleteChunk(arg0 context.Context, arg1 types.ObjectSlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChunk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChunk indicates an expected call of DeleteChunk.
func (mr *MockObjectRWMockRecorder) DeleteChunk(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChunk", reflect.TypeOf((*MockObjectRW)(nil).DeleteChunk), arg0, arg1)
}

// Exists mocks base method.
func (m *MockObjectRW) Exists(ctx context.Context, objectID types.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, objectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockObjectRWMockRecorder) Exists(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockObjectRW)(nil).Exists), ctx, objectID)
}

// ExistsChunk mocks base method.
func (m *MockObjectRW) ExistsChunk(ctx context.Context, slot types.ObjectSlot) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsChunk", ctx, slot)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsChunk indicates an expected call of ExistsChunk.
func (mr *MockObjectRWMockRecorder) ExistsChunk(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsChunk", reflect.TypeOf((*MockObjectRW)(nil).ExistsChunk), ctx, slot)
}

// Get mocks base method.
func (m *MockObjectRW) Get(ctx context.Context, objectID types.ObjectID) (master.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, objectID)
	ret0, _ := ret[0].(master.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObjectRWMockRecorder) Get(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectRW)(nil).Get), ctx, objectID)
}

// GetChunk mocks base method.
func (m *MockObjectRW) GetChunk(ctx context.Context, slot types.ObjectSlot) (types.ChunkID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunk", ctx, slot)
	ret0, _ := ret[0].(types.ChunkID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunk indicates an expected call of GetChunk.
func (mr *MockObjectRWMockRecorder) GetChunk(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunk", reflect.TypeOf((*MockObjectRW)(nil).GetChunk), ctx, slot)
}

// GetReplication mocks base method.
func (m *MockObjectRW) GetReplication(ctx context.Context, objectID types.ObjectID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplication", ctx, objectID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplication indicates an expected call of GetReplication.
func (mr *MockObjectRWMockRecorder) GetReplication(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplication", reflect.TypeOf((*MockObjectRW)(nil).GetReplication), ctx, objectID)
}

// List mocks base method.
func (m *MockObjectRW) List(ctx context.Context) []master.Object {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]master.Object)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockObjectRWMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockObjectRW)(nil).List), ctx)
}

// SetReplication mocks base method.
func (m *MockObjectRW) SetReplication(arg0 context.Context, arg1 types.ObjectID, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReplication", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReplication indicates an expected call of SetReplication.
func (mr *MockObjectRWMockRecorder) SetReplication(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReplication", reflect.TypeOf((*MockObjectRW)(nil).SetReplication), arg0, arg1, arg2)
}
