// Code generated by MockGen. DO NOT EDIT.
// Source: report.go
//
// Generated by this command:
//
//	mockgen -source=report.go -destination=report_mocks_test.go -package=report
//

// Package report is a generated GoMock package.
package report

import (
	context "context"
	types "dos/internal/common/types"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockReportConfig is a mock of ReportConfig interface.
type MockReportConfig struct {
	ctrl     *gomock.Controller
	recorder *MockReportConfigMockRecorder
	isgomock struct{}
}

// MockReportConfigMockRecorder is the mock recorder for MockReportConfig.
type MockReportConfigMockRecorder struct {
	mock *MockReportConfig
}

// NewMockReportConfig creates a new mock instance.
func NewMockReportConfig(ctrl *gomock.Controller) *MockReportConfig {
	mock := &MockReportConfig{ctrl: ctrl}
	mock.recorder = &MockReportConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportConfig) EXPECT() *MockReportConfigMockRecorder {
	return m.recorder
}

// QueueCapacity mocks base method.
func (m *MockReportConfig) QueueCapacity() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueCapacity")
	ret0, _ := ret[0].(int)
	return ret0
}

// QueueCapacity indicates an expected call of QueueCapacity.
func (mr *MockReportConfigMockRecorder) QueueCapacity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueCapacity", reflect.TypeOf((*MockReportConfig)(nil).QueueCapacity))
}

// ReportInterval mocks base method.
func (m *MockReportConfig) ReportInterval() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportInterval")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ReportInterval indicates an expected call of ReportInterval.
func (mr *MockReportConfigMockRecorder) ReportInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportInterval", reflect.TypeOf((*MockReportConfig)(nil).ReportInterval))
}

// MockIdentityProvider is a mock of IdentityProvider interface.
type MockIdentityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityProviderMockRecorder
	isgomock struct{}
}

// MockIdentityProviderMockRecorder is the mock recorder for MockIdentityProvider.
type MockIdentityProviderMockRecorder struct {
	mock *MockIdentityProvider
}

// NewMockIdentityProvider creates a new mock instance.
func NewMockIdentityProvider(ctrl *gomock.Controller) *MockIdentityProvider {
	mock := &MockIdentityProvider{ctrl: ctrl}
	mock.recorder = &MockIdentityProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityProvider) EXPECT() *MockIdentityProviderMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockIdentityProvider) GetID() (types.NodeID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(types.NodeID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockIdentityProviderMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockIdentityProvider)(nil).GetID))
}

// MockReportProcessor is a mock of ReportProcessor interface.
type MockReportProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockReportProcessorMockRecorder
	isgomock struct{}
}

// MockReportProcessorMockRecorder is the mock recorder for MockReportProcessor.
type MockReportProcessorMockRecorder struct {
	mock *MockReportProcessor
}

// NewMockReportProcessor creates a new mock instance.
func NewMockReportProcessor(ctrl *gomock.Controller) *MockReportProcessor {
	mock := &MockReportProcessor{ctrl: ctrl}
	mock.recorder = &MockReportProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportProcessor) EXPECT() *MockReportProcessorMockRecorder {
	return m.recorder
}

// ProcessReport mocks base method.
func (m *MockReportProcessor) ProcessReport(arg0 context.Context, arg1 types.ReportResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessReport", arg0, arg1)
}

// ProcessReport indicates an expected call of ProcessReport.
func (mr *MockReportProcessorMockRecorder) ProcessReport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessReport", reflect.TypeOf((*MockReportProcessor)(nil).ProcessReport), arg0, arg1)
}

// MockMasterTransport is a mock of MasterTransport interface.
type MockMasterTransport struct {
	ctrl     *gomock.Controller
	recorder *MockMasterTransportMockRecorder
	isgomock struct{}
}

// MockMasterTransportMockRecorder is the mock recorder for MockMasterTransport.
type MockMasterTransportMockRecorder struct {
	mock *MockMasterTransport
}

// NewMockMasterTransport creates a new mock instance.
func NewMockMasterTransport(ctrl *gomock.Controller) *MockMasterTransport {
	mock := &MockMasterTransport{ctrl: ctrl}
	mock.recorder = &MockMasterTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterTransport) EXPECT() *MockMasterTransportMockRecorder {
	return m.recorder
}

// ReportChunks mocks base method.
func (m *MockMasterTransport) ReportChunks(arg0 context.Context, arg1 types.NodeID, arg2 []types.StorageNodeReport) (types.ReportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportChunks", arg0, arg1, arg2)
	ret0, _ := ret[0].(types.ReportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportChunks indicates an expected call of ReportChunks.
func (mr *MockMasterTransportMockRecorder) ReportChunks(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportChunks", reflect.TypeOf((*MockMasterTransport)(nil).ReportChunks), arg0, arg1, arg2)
}
