logger:
  level: debug
  component: master

listen:
  host: "0.0.0.0"
  port: 10000

master:
  self: master
  peers:
    - id: master0
      api_addr: master0:10000
      raft_addr: master0:12000
    - id: master1
      api_addr: master1:10000
      raft_addr: master1:12000
    - id: master2
      api_addr: master2:10000
      raft_addr: master2:12000

metrics:
  scrape_port: 9100
  scrape_path: /metrics
  namespace: dos

raft:
  enable: true
  bootstrap: true
  apply_timeout: 1s
  snapshot_interval: 10m
  snapshot_threshold: 1000000

service:
  frame_size: 3MB
  replication_count: 1
  chunk_allocation_margin_bytes: 512
  node_inactivity_timeout: 3s
  node_cleanup_interval: 3s
  replication_queue_length: 100
  catalog_cleanup_interval: 3s
  replication_interval: 3s
  chunk_stale_after: 3s
  replication_planner_interval: 3s
  rpc_timeout: 10s
