logger:
  level: debug
  component: master

listen:
  host: "0.0.0.0"
  port: 10000

service:
  replication_count: 1
  chunk_allocation_margin_bytes: 512 
  node_inactivity_timeout: 30s
  node_cleanup_interval: 15s
  replication_queue_length: 100
  catalog_cleanup_interval: 20s
