cli:
  output: text
  render_refresh: 0.2s

client:
  frame_size: 3MB 
  chunk_size: 20MB
  concurrency: 4  
  rpc_timeout: 10s

master:
  api_port: 10000
  peers:
    - master-0
    - master-1
    - master-2
