cli:
  output: text
  render_refresh: 0.2s

client:
  frame_size: 1MB 
  chunk_size: 5MB
  concurrency: 4  

master:
  peers:
    - id: master0
      api_addr: master0:10000
    - id: master1
      api_addr: master1:10000
    - id: master2
      api_addr: master2:10000
