// Code generated by MockGen. DO NOT EDIT.
// Source: transport.go
//
// Generated by this command:
//
//	mockgen -source=transport.go -destination=mock/session_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	types "dos/internal/common/types"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
	isgomock struct{}
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// FrameSize mocks base method.
func (m *MockConfig) FrameSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FrameSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FrameSize indicates an expected call of FrameSize.
func (mr *MockConfigMockRecorder) FrameSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FrameSize", reflect.TypeOf((*MockConfig)(nil).FrameSize))
}

// RPCTimeout mocks base method.
func (m *MockConfig) RPCTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RPCTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RPCTimeout indicates an expected call of RPCTimeout.
func (mr *MockConfigMockRecorder) RPCTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RPCTimeout", reflect.TypeOf((*MockConfig)(nil).RPCTimeout))
}

// MockUploadSession is a mock of UploadSession interface.
type MockUploadSession struct {
	ctrl     *gomock.Controller
	recorder *MockUploadSessionMockRecorder
	isgomock struct{}
}

// MockUploadSessionMockRecorder is the mock recorder for MockUploadSession.
type MockUploadSessionMockRecorder struct {
	mock *MockUploadSession
}

// NewMockUploadSession creates a new mock instance.
func NewMockUploadSession(ctrl *gomock.Controller) *MockUploadSession {
	mock := &MockUploadSession{ctrl: ctrl}
	mock.recorder = &MockUploadSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadSession) EXPECT() *MockUploadSessionMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploadSession) Upload(arg0 context.Context, arg1 *types.Chunk) (types.NodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0, arg1)
	ret0, _ := ret[0].(types.NodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockUploadSessionMockRecorder) Upload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploadSession)(nil).Upload), arg0, arg1)
}

// MockDownloadSession is a mock of DownloadSession interface.
type MockDownloadSession struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadSessionMockRecorder
	isgomock struct{}
}

// MockDownloadSessionMockRecorder is the mock recorder for MockDownloadSession.
type MockDownloadSessionMockRecorder struct {
	mock *MockDownloadSession
}

// NewMockDownloadSession creates a new mock instance.
func NewMockDownloadSession(ctrl *gomock.Controller) *MockDownloadSession {
	mock := &MockDownloadSession{ctrl: ctrl}
	mock.recorder = &MockDownloadSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadSession) EXPECT() *MockDownloadSessionMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockDownloadSession) Download(arg0 context.Context, arg1 types.ChunkID) (types.Chunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", arg0, arg1)
	ret0, _ := ret[0].(types.Chunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockDownloadSessionMockRecorder) Download(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockDownloadSession)(nil).Download), arg0, arg1)
}
