// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	chunkrpc "dos/internal/common/transport/chunkrpc"
	types "dos/internal/common/types"
	storage "dos/internal/services/storage"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageConfig is a mock of StorageConfig interface.
type MockStorageConfig struct {
	ctrl     *gomock.Controller
	recorder *MockStorageConfigMockRecorder
	isgomock struct{}
}

// MockStorageConfigMockRecorder is the mock recorder for MockStorageConfig.
type MockStorageConfigMockRecorder struct {
	mock *MockStorageConfig
}

// NewMockStorageConfig creates a new mock instance.
func NewMockStorageConfig(ctrl *gomock.Controller) *MockStorageConfig {
	mock := &MockStorageConfig{ctrl: ctrl}
	mock.recorder = &MockStorageConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageConfig) EXPECT() *MockStorageConfigMockRecorder {
	return m.recorder
}

// AdvertiseAddr mocks base method.
func (m *MockStorageConfig) AdvertiseAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvertiseAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// AdvertiseAddr indicates an expected call of AdvertiseAddr.
func (mr *MockStorageConfigMockRecorder) AdvertiseAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvertiseAddr", reflect.TypeOf((*MockStorageConfig)(nil).AdvertiseAddr))
}

// MaxParallelHeavyOps mocks base method.
func (m *MockStorageConfig) MaxParallelHeavyOps() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxParallelHeavyOps")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxParallelHeavyOps indicates an expected call of MaxParallelHeavyOps.
func (mr *MockStorageConfigMockRecorder) MaxParallelHeavyOps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxParallelHeavyOps", reflect.TypeOf((*MockStorageConfig)(nil).MaxParallelHeavyOps))
}

// ReplicationTimeout mocks base method.
func (m *MockStorageConfig) ReplicationTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicationTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ReplicationTimeout indicates an expected call of ReplicationTimeout.
func (mr *MockStorageConfigMockRecorder) ReplicationTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicationTimeout", reflect.TypeOf((*MockStorageConfig)(nil).ReplicationTimeout))
}

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockReporter) Flush(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush", arg0)
}

// Flush indicates an expected call of Flush.
func (mr *MockReporterMockRecorder) Flush(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockReporter)(nil).Flush), arg0)
}

// Report mocks base method.
func (m *MockReporter) Report(arg0 context.Context, arg1 types.StorageNodeReport) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Report", arg0, arg1)
}

// Report indicates an expected call of Report.
func (mr *MockReporterMockRecorder) Report(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockReporter)(nil).Report), arg0, arg1)
}

// MockIdentity is a mock of Identity interface.
type MockIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityMockRecorder
	isgomock struct{}
}

// MockIdentityMockRecorder is the mock recorder for MockIdentity.
type MockIdentityMockRecorder struct {
	mock *MockIdentity
}

// NewMockIdentity creates a new mock instance.
func NewMockIdentity(ctrl *gomock.Controller) *MockIdentity {
	mock := &MockIdentity{ctrl: ctrl}
	mock.recorder = &MockIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentity) EXPECT() *MockIdentityMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockIdentity) GetID() (types.NodeID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(types.NodeID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockIdentityMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockIdentity)(nil).GetID))
}

// MockChunkTransport is a mock of ChunkTransport interface.
type MockChunkTransport struct {
	ctrl     *gomock.Controller
	recorder *MockChunkTransportMockRecorder
	isgomock struct{}
}

// MockChunkTransportMockRecorder is the mock recorder for MockChunkTransport.
type MockChunkTransportMockRecorder struct {
	mock *MockChunkTransport
}

// NewMockChunkTransport creates a new mock instance.
func NewMockChunkTransport(ctrl *gomock.Controller) *MockChunkTransport {
	mock := &MockChunkTransport{ctrl: ctrl}
	mock.recorder = &MockChunkTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkTransport) EXPECT() *MockChunkTransportMockRecorder {
	return m.recorder
}

// NewUploadSession mocks base method.
func (m *MockChunkTransport) NewUploadSession(arg0 []types.NodeRef, arg1 ...chunkrpc.SessionOption) ChunkUploadSession {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewUploadSession", varargs...)
	ret0, _ := ret[0].(ChunkUploadSession)
	return ret0
}

// NewUploadSession indicates an expected call of NewUploadSession.
func (mr *MockChunkTransportMockRecorder) NewUploadSession(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUploadSession", reflect.TypeOf((*MockChunkTransport)(nil).NewUploadSession), varargs...)
}

// ReplicateChunk mocks base method.
func (m *MockChunkTransport) ReplicateChunk(arg0 context.Context, arg1 types.ChunkID, arg2 types.NodeRef, arg3 []types.NodeRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicateChunk", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplicateChunk indicates an expected call of ReplicateChunk.
func (mr *MockChunkTransportMockRecorder) ReplicateChunk(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicateChunk", reflect.TypeOf((*MockChunkTransport)(nil).ReplicateChunk), arg0, arg1, arg2, arg3)
}

// MockInventory is a mock of Inventory interface.
type MockInventory struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryMockRecorder
	isgomock struct{}
}

// MockInventoryMockRecorder is the mock recorder for MockInventory.
type MockInventoryMockRecorder struct {
	mock *MockInventory
}

// NewMockInventory creates a new mock instance.
func NewMockInventory(ctrl *gomock.Controller) *MockInventory {
	mock := &MockInventory{ctrl: ctrl}
	mock.recorder = &MockInventoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventory) EXPECT() *MockInventoryMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockInventory) Activate(arg0 types.ChunkID) (types.ChunkMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", arg0)
	ret0, _ := ret[0].(types.ChunkMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activate indicates an expected call of Activate.
func (mr *MockInventoryMockRecorder) Activate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockInventory)(nil).Activate), arg0)
}

// Add mocks base method.
func (m *MockInventory) Add(arg0 *types.ChunkMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockInventoryMockRecorder) Add(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockInventory)(nil).Add), arg0)
}

// BuildCatalog mocks base method.
func (m *MockInventory) BuildCatalog(arg0 context.Context, arg1 storage.CatalogSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCatalog", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildCatalog indicates an expected call of BuildCatalog.
func (mr *MockInventoryMockRecorder) BuildCatalog(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCatalog", reflect.TypeOf((*MockInventory)(nil).BuildCatalog), arg0, arg1)
}

// GetRecord mocks base method.
func (m *MockInventory) GetRecord(arg0 types.ChunkID) (*storage.ChunkRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecord", arg0)
	ret0, _ := ret[0].(*storage.ChunkRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecord indicates an expected call of GetRecord.
func (mr *MockInventoryMockRecorder) GetRecord(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecord", reflect.TypeOf((*MockInventory)(nil).GetRecord), arg0)
}

// Has mocks base method.
func (m *MockInventory) Has(arg0 types.ChunkID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockInventoryMockRecorder) Has(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockInventory)(nil).Has), arg0)
}

// ListIDs mocks base method.
func (m *MockInventory) ListIDs() []types.ChunkID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIDs")
	ret0, _ := ret[0].([]types.ChunkID)
	return ret0
}

// ListIDs indicates an expected call of ListIDs.
func (mr *MockInventoryMockRecorder) ListIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIDs", reflect.TypeOf((*MockInventory)(nil).ListIDs))
}

// Remove mocks base method.
func (m *MockInventory) Remove(arg0 types.ChunkID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockInventoryMockRecorder) Remove(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockInventory)(nil).Remove), arg0)
}

// Stage mocks base method.
func (m *MockInventory) Stage(arg0 types.ChunkID) (types.ChunkMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stage", arg0)
	ret0, _ := ret[0].(types.ChunkMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stage indicates an expected call of Stage.
func (mr *MockInventoryMockRecorder) Stage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stage", reflect.TypeOf((*MockInventory)(nil).Stage), arg0)
}

// MockChunkStorage is a mock of ChunkStorage interface.
type MockChunkStorage struct {
	ctrl     *gomock.Controller
	recorder *MockChunkStorageMockRecorder
	isgomock struct{}
}

// MockChunkStorageMockRecorder is the mock recorder for MockChunkStorage.
type MockChunkStorageMockRecorder struct {
	mock *MockChunkStorage
}

// NewMockChunkStorage creates a new mock instance.
func NewMockChunkStorage(ctrl *gomock.Controller) *MockChunkStorage {
	mock := &MockChunkStorage{ctrl: ctrl}
	mock.recorder = &MockChunkStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkStorage) EXPECT() *MockChunkStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockChunkStorage) Delete(arg0 types.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChunkStorageMockRecorder) Delete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChunkStorage)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockChunkStorage) Get(arg0 types.ChunkID) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockChunkStorageMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockChunkStorage)(nil).Get), arg0)
}

// GetMeta mocks base method.
func (m *MockChunkStorage) GetMeta(arg0 types.ChunkID) (types.ChunkMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeta", arg0)
	ret0, _ := ret[0].(types.ChunkMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeta indicates an expected call of GetMeta.
func (mr *MockChunkStorageMockRecorder) GetMeta(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeta", reflect.TypeOf((*MockChunkStorage)(nil).GetMeta), arg0)
}

// List mocks base method.
func (m *MockChunkStorage) List() ([]types.ChunkID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]types.ChunkID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockChunkStorageMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockChunkStorage)(nil).List))
}

// Store mocks base method.
func (m *MockChunkStorage) Store(chunk types.Chunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", chunk)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockChunkStorageMockRecorder) Store(chunk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockChunkStorage)(nil).Store), chunk)
}
