apiVersion: v1
kind: ConfigMap
metadata:
  name: dos-config
  namespace: dos
data:  
  DEFAULT_REPLICATION: "1"
  FRAME_SIZE: "3MB"
  RPC_TIMEOUT: "10s"
  CHUNK_SIZE: "20MB"
  HEARTBEAT_INTERVAL: "1s"
  REPORT_INTERVAL: "3s"
  MAX_PARALLEL_HEAVY_OPS: "4"
