apiVersion: batch/v1
kind: Job
metadata:
  name: dos-e2e-test
  namespace: dos
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: test
          image: dos-test:latest
          imagePullPolicy: Never
          command: ["pytest", "-v", "tests/e2e"]
          env:
            - name: MASTER__PEERS
              value: "master-0.master,master-1.master,master-2.master"
